name: Upload Artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "**/.gitignore"
      - "**/.dockerignore"
      - LICENSE
      - "**/*.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "**/.gitignore"
      - "**/.dockerignore"
      - LICENSE
      - "**/*.md"

jobs:
  linux:
    uses: ./.github/workflows/build_linux.yml
    secrets: inherit

  windows:
    uses: ./.github/workflows/build_windows.yml
    secrets: inherit

  upload:
    runs-on: ubuntu-latest
    needs: [linux, windows]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip artifact
        id: zip
        run: |
          echo "zip_files<<EOF" >> "$GITHUB_OUTPUT"
          find artifacts/ -mindepth 1 -maxdepth 1 -type d | while read -r dir; do
            zip -r "${dir}.zip" "$dir" >> /dev/null
            echo "${dir}.zip"
          done >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
